repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: no-commit-to-branch # prevent direct commits to main
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        language_version: python3
        args:
          [--line-length=100]
          # - repo: https://github.com/pre-commit/mirrors-mypy
          #   rev: v1.4.1
          #   hooks:
          #     - id: mypy
          #       additional_dependencies: [pydantic]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.292
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@2.8.0
          - prettier-plugin-svelte@v2.8.1
          - svelte@v3.54.0
