version: "3"

services:
  backend:
    image: backend:dev
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - achievaim
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo_password
      - MONGO_PORT=27017
      - MONGO_HOST=db
      - SECRET_KEY=secret
  db:
    image: mongo:6.0
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo_password
    expose:
      - 27017
    networks:
      - achievaim
    ports:
      - "27017:27017"

networks:
  achievaim:
